<#
.SYNOPSIS
  Writes everything the Lead has asked of the owner into one readable note, newest first, so nothing is lost when the
  Lead pane scrolls, is cleared, or the owner is asleep.
.DESCRIPTION
  Source: the Lead's Claude Code session files (~/.claude/projects/C--Dev-vault-companion/*.jsonl). They hold every
  message, survive /clear and restarts, and need no screen scraping. Output: an Obsidian note in the vault (default
  Projects/Vault Companion/Lead - Action Needed Log.md) with two sections: ACTION NEEDED messages (full text) and the
  latest STATUS lines. Re-run any time; the file is rewritten from the transcripts, so it never duplicates.
  tools/lead-watch.ps1 calls this every few minutes. Run by hand:  pwsh -NoProfile -File tools/action-log.ps1
#>
param(
    [string]$Out = (Join-Path ([Environment]::GetFolderPath('UserProfile')) 'Obsidian Vault/Second Brain/Projects/Vault Companion/Lead - Action Needed Log.md'),
    [string]$Sessions = (Join-Path ([Environment]::GetFolderPath('UserProfile')) '.claude/projects/C--Dev-vault-companion'),
    [int]$Hours = 24,
    [int]$MaxStatus = 25
)
$ErrorActionPreference = 'Stop'
$since = (Get-Date).AddHours(-$Hours)
$actions = [System.Collections.Generic.List[object]]::new()
$statuses = [System.Collections.Generic.List[object]]::new()

foreach ($file in Get-ChildItem -LiteralPath $Sessions -Filter *.jsonl | Where-Object { $_.LastWriteTime -ge $since }) {
    # Cheap prefilter: only lines that can hold either marker are parsed as JSON.
    foreach ($line in [System.IO.File]::ReadLines($file.FullName)) {
        if ($line -notlike '*ACTION NEEDED*' -and $line -notlike '*STATUS:*') { continue }
        try { $d = $line | ConvertFrom-Json -ErrorAction Stop } catch { continue }
        if ($d.type -ne 'assistant' -or -not $d.message -or $d.message.role -ne 'assistant') { continue }
        $text = (@($d.message.content) | Where-Object { $_.type -eq 'text' } | ForEach-Object { $_.text }) -join "`n"
        if (-not $text) { continue }
        $when = [datetime]::Parse($d.timestamp, [Globalization.CultureInfo]::InvariantCulture).ToLocalTime()
        if ($when -lt $since) { continue }
        $m = [regex]::Match($text, '(?ms)^\W*ACTION NEEDED:.*')
        if ($m.Success) {
            $body = ($m.Value -replace '(?m)^\W*LEAD-RESTART-NOW\W*$', '').Trim()
            $actions.Add([pscustomobject]@{ When = $when; Text = $body })
        }
        $s = [regex]::Match($text, '(?m)^\W*(STATUS:.*)$')
        if ($s.Success) { $statuses.Add([pscustomobject]@{ When = $when; Text = $s.Groups[1].Value.Trim() }) }
    }
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('---')
[void]$sb.AppendLine('title: Lead - Action Needed Log')
[void]$sb.AppendLine("updated: $(Get-Date -Format 'yyyy-MM-dd HH:mm')")
[void]$sb.AppendLine('type: log')
[void]$sb.AppendLine('tags:')
[void]$sb.AppendLine('  - vault-companion')
[void]$sb.AppendLine('  - lead-agent')
[void]$sb.AppendLine('---')
[void]$sb.AppendLine()
[void]$sb.AppendLine('# Lead - Action Needed Log')
[void]$sb.AppendLine()
[void]$sb.AppendLine("Generated by ``tools/action-log.ps1`` from the Lead's session files at $(Get-Date -Format 'yyyy-MM-dd HH:mm'). Last $Hours hours, newest first. An older item may already be handled: check the STATUS lines below it first.")
[void]$sb.AppendLine()
[void]$sb.AppendLine("## ACTION NEEDED ($($actions.Count))")
[void]$sb.AppendLine()
if ($actions.Count -eq 0) { [void]$sb.AppendLine('Nothing asked of you in this period.') }
foreach ($a in ($actions | Sort-Object When -Descending)) {
    [void]$sb.AppendLine("### $($a.When.ToString('yyyy-MM-dd HH:mm'))")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine($a.Text)
    [void]$sb.AppendLine()
}
[void]$sb.AppendLine("## Latest STATUS lines (up to $MaxStatus)")
[void]$sb.AppendLine()
foreach ($x in ($statuses | Sort-Object When -Descending | Select-Object -First $MaxStatus)) {
    $t = if ($x.Text.Length -gt 400) { $x.Text.Substring(0, 400) + '...' } else { $x.Text }
    [void]$sb.AppendLine("- $($x.When.ToString('MM-dd HH:mm')) $t")
}

$dir = Split-Path -Parent $Out
if (-not (Test-Path -LiteralPath $dir)) { throw "Output folder not found: $dir" }
# Write only when the content changed (ignoring the generated-at stamps) so Obsidian sync and Git are not churned.
$new = $sb.ToString()
$strip = { param($s) ($s -replace '(?m)^updated: .*$', '' -replace 'at \d{4}-\d\d-\d\d \d\d:\d\d\. Last', 'at X. Last') }
$old = if (Test-Path -LiteralPath $Out) { Get-Content -LiteralPath $Out -Raw } else { '' }
if ((& $strip $old) -ne (& $strip $new)) { Set-Content -LiteralPath $Out -Value $new -Encoding utf8 }
Write-Output "action-log: $($actions.Count) ACTION NEEDED, $($statuses.Count) STATUS lines -> $Out"
