# Create (never execute) the Claude Lead launcher for this repo.
# Usage: pwsh -NoProfile -File tools/start-lead.ps1
param([string]$Out = "C:/Dev/tmp/vault-companion/start-lead.launch.ps1")
$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
$profile = Get-Content (Join-Path $repo 'tools/profiles/lead.profile.json') -Raw | ConvertFrom-Json
$mcp = Get-Content (Join-Path $repo 'tools/profiles/lead.mcp.json') -Raw | ConvertFrom-Json

# Pinned invariants: refuse to produce a launcher if any of them are missing.
if ($profile.env.ENABLE_CLAUDEAI_MCP_SERVERS -ne 'false') { throw 'ENABLE_CLAUDEAI_MCP_SERVERS must be false' }
if ($profile.model -ne 'claude-opus-5-5') { throw 'Lead model must be claude-opus-5-5' }
if ($profile.effort -ne 'high') { throw 'Lead effort must be high' }
if ($profile.allowCloudflareExecute -ne $false) { throw 'Cloudflare execute must stay disabled' }
$servers = @($mcp.mcpServers.PSObject.Properties | ForEach-Object { $_.Name })
if (Compare-Object @('context7', 'playwright') $servers) { throw 'Lead MCP must pin exactly context7 and playwright' }

$mcpPath = Join-Path $repo $profile.mcpConfig
$launcher = @"
# Generated by tools/start-lead.ps1. Run only when the Lead is ready to resume (never automatically).
`$env:ENABLE_CLAUDEAI_MCP_SERVERS='false'
claude --model "$($profile.model)" --effort "$($profile.effort)" --mcp-config "$mcpPath" --strict-mcp-config
"@
New-Item -ItemType Directory -Force -Path (Split-Path $Out) | Out-Null
[System.IO.File]::WriteAllText($Out, $launcher, (New-Object System.Text.UTF8Encoding($false)))
Write-Output "Lead launcher written: $Out (not executed)"
